// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: changePW/changePW.proto

package changePW

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token       string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	OldPassword string `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword string `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
}

func (x *ChangeReq) Reset() {
	*x = ChangeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_changePW_changePW_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeReq) ProtoMessage() {}

func (x *ChangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_changePW_changePW_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeReq.ProtoReflect.Descriptor instead.
func (*ChangeReq) Descriptor() ([]byte, []int) {
	return file_changePW_changePW_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ChangeReq) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangeReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"` //提示信息
}

func (x *ChangeRes) Reset() {
	*x = ChangeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_changePW_changePW_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRes) ProtoMessage() {}

func (x *ChangeRes) ProtoReflect() protoreflect.Message {
	mi := &file_changePW_changePW_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRes.ProtoReflect.Descriptor instead.
func (*ChangeRes) Descriptor() ([]byte, []int) {
	return file_changePW_changePW_proto_rawDescGZIP(), []int{1}
}

func (x *ChangeRes) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ChangeRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_changePW_changePW_proto protoreflect.FileDescriptor

var file_changePW_changePW_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x57, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x50, 0x57, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x50, 0x57, 0x22, 0x67, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x6c, 0x64, 0x5f, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x6c,
	0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x65, 0x77,
	0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x35, 0x0a, 0x09,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x32, 0x40, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x57, 0x12,
	0x34, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x57, 0x12, 0x13, 0x2e, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x50, 0x57, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x57, 0x2e, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x50, 0x57, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_changePW_changePW_proto_rawDescOnce sync.Once
	file_changePW_changePW_proto_rawDescData = file_changePW_changePW_proto_rawDesc
)

func file_changePW_changePW_proto_rawDescGZIP() []byte {
	file_changePW_changePW_proto_rawDescOnce.Do(func() {
		file_changePW_changePW_proto_rawDescData = protoimpl.X.CompressGZIP(file_changePW_changePW_proto_rawDescData)
	})
	return file_changePW_changePW_proto_rawDescData
}

var file_changePW_changePW_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_changePW_changePW_proto_goTypes = []interface{}{
	(*ChangeReq)(nil), // 0: changePW.changeReq
	(*ChangeRes)(nil), // 1: changePW.changeRes
}
var file_changePW_changePW_proto_depIdxs = []int32{
	0, // 0: changePW.changePW.changePW:input_type -> changePW.changeReq
	1, // 1: changePW.changePW.changePW:output_type -> changePW.changeRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_changePW_changePW_proto_init() }
func file_changePW_changePW_proto_init() {
	if File_changePW_changePW_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_changePW_changePW_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_changePW_changePW_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_changePW_changePW_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_changePW_changePW_proto_goTypes,
		DependencyIndexes: file_changePW_changePW_proto_depIdxs,
		MessageInfos:      file_changePW_changePW_proto_msgTypes,
	}.Build()
	File_changePW_changePW_proto = out.File
	file_changePW_changePW_proto_rawDesc = nil
	file_changePW_changePW_proto_goTypes = nil
	file_changePW_changePW_proto_depIdxs = nil
}
